import ButtonPage from "./pages/button/button.page";
import InputPage from "./pages/input/input.page";
import TextAreaPage from "./pages/textarea/textarea.page";
import SelectPage from "./pages/select/select.page";
import ComponentPage from "./pages/component/component.page";
import CheckboxPage from "./pages/checkbox/checkbox.page";
import RadioPage from "./pages/radio/radio.page";
import UploadPage from "./pages/fileUpload/upload.page";
import BoxPage from "./pages/box/box.page";
import ContentPage from "./pages/content/content.page";
import ImageContainerPage from "./pages/imageContainer/imageContainer.page";
import NotificationPage from "./pages/notification/notification.page";
import ProgressBarPage from "./pages/progressBar/progressBar.page";
import TagPage from "./pages/tag/tag.page";
import BreadcrumbPage from "./pages/breadcrumb/breadcrumb.page";

export const Component = ComponentPage;
export const Button = ButtonPage;
export const Input = InputPage;
export const TextArea = TextAreaPage;
export const Select = SelectPage;
export const Checkbox = CheckboxPage;
export const Radio = RadioPage;
export const Upload = UploadPage;
export const Box = BoxPage;
export const Content = ContentPage;
export const ImageContainer = ImageContainerPage;
export const Notification = NotificationPage;
export const ProgressBar = ProgressBarPage;
export const Tag = TagPage;
export const Breadcrumb = BreadcrumbPage;
